
recorder:
  exclude:
    entities:
      - sensor.sprinkler_config
      - script.sprinkler_log_message

logbook:
  exclude:
    entities:
      - sensor.sprinkler_config
      - script.sprinkler_log_message



template:


  # ---------- Configuration sensor -------------------
  - triggers:
      - trigger: homeassistant
        event: start

      - platform: event
        event_type: event_template_reloaded

    variables:
      programs:
        The Hose on the Hill:
          Left side of path up hill two sprinklers:
            - switch.sprinkler_valve_22
            - 20
        Native Plant drips:
          Hot tub & wall Drips:
            - switch.sprinkler_valve_01
            - 33
          Planters by kitchen & living room:
            - switch.sprinkler_valve_20
            - 33
          Hillside and fountain drips:
            - switch.sprinkler_valve_24
            - 33
        Established Drips:
          West Berm by road:
            - switch.sprinkler_valve_21
            - 44
          Bedroom, horseshoe pit drips:
            - switch.sprinkler_valve_03
            - 44
          North driveway drips:
            - switch.sprinkler_valve_07
            - 44
          North & east fence drips:
            - switch.sprinkler_valve_08
            - 44
          North of front path drips:
            - switch.sprinkler_valve_18
            - 44
          South hill, fence drips:
            - switch.sprinkler_valve_19
            - 44
          Front south of sidewalk & deck drips:
            - switch.sprinkler_valve_27
            - 44
        Lawn and Tall Grass:
          Lawn pop-ups:
            - switch.sprinkler_valve_25
            - 15
          Long grass south pop-ups:
            - switch.sprinkler_valve_26
            - 15
          Long grass north section pop-ups:
            - switch.sprinkler_valve_17
            - 15
        Vinca Heads:
          North lower 4 sprinklers:
            - switch.sprinkler_valve_09
            - 22
          North upper 3 sprinklers:
            - switch.sprinkler_valve_10
            - 22
          Left side of path up hill two sprinklers:
            - switch.sprinkler_valve_22
            - 0
          Hill redwoods sprinklers:
            - switch.sprinkler_valve_23
            - 22

    sensor:
      - name: Sprinkler Config
        unique_id: sprinkler_config_id
        default_entity_id: sensor.sprinkler_config
        state: "{{ now() }}"
        attributes:
          programs: "{{ programs }}"



# ======= Helpers ========

input_text:

  # The script.sprinkler_log_message updates this. Using a script so it can be "queued" to not drop messages.
  # See https://community.home-assistant.io/t/wth-no-queued-or-restart-mode-for-trigger-based-template-sensor-action/819289?
  sprinkler_log_message:



script:

  # This is a queued scirpt for writing "logs" to a input_text's state so that the custom:logbook-card can display it.
  # Using a script so it can be "queued" and thus have to update an input_select (not a trigger-based template sensor).
  # See: https://community.home-assistant.io/t/wth-no-queued-or-restart-mode-for-trigger-based-template-sensor-action/819289

  sprinkler_log_message:
    mode: queued
    alias: Updates a text sensor based on the passed in message and user
    fields:
      message:
        name: Message to add to the logs
        required: true
        selector:
          text:
      usere:
        name: User to prefix the log with
        required: true
        selector:
          text:
    sequence:
      - action: input_text.set_value
        target:
          entity_id: input_text.sprinkler_log_message
        data:
          value: "{{ message }} by {{ user }}"



  sprinkler_get_minutes:
    mode: queued
    fields:
      program:
        name: Selected program Name
      valve:
        name: Selected valve Name

    sequence:
      - variables:
          programs: "{{ state_attr('sensor.sprinkler_config','programs') }}"
          conf_min: "{{ programs.get(program,{}).get(valve,[1,0])[1]}}"
          percent: "{{ states('input_number.sprinkler_valve_percent_runtime')|default(100,true) }}"
          data:
            minutes: "{{ (conf_min|int * percent|int /100)|int }}"

      - stop: Calculated Minutes
        response_variable: data

