# ------------------------ Running the irrigation --------------------------------
#
# The key here is timer.
#   - Valve opens when timer starts, and closes when stopped or paused
#   - If timer "finishes" (not canceled) then set new queue position
#   - When queue position changes start timer?


recorder:
  exclude:
    entities:
      - switch.sprinkler_master_switch
      - sensor.sprinkler_display_message
      - sensor.sprinkler_remaining_time

logbook:
  exclude:
    entities:
      - switch.sprinkler_master_switch
      - sensor.sprinkler_display_message
      - sensor.sprinkler_remaining_time


#=====================================================================================

timer:
  sprinkler_valve_time:
    restore: true


template:


  # Master on/off. This is NOT for general use. For seasonal shut-off just turn
  # off the schedule which still allows manual operation of programs or valves.
  # The purpose here is to have an abstraction to stop all use, e.g. in the case
  # of low water pressure. It will "pause" a running timer and prevent any running
  # of schedules, programs, or valves.
  # I'm using a "switch" here because it runs actions on changes unlike a binary sensor.
  # TODO: In general, there's a time limit on a pause to prevent forgetting about it
  # and then blocking future schedules from running. What should happen here?
  # Maybe the better solution is to allow a schedule to override a pause IF the
  # pause has been running too long?
  #
  - switch:
      name: Sprinkler Master Switch
      default_entity_id: switch.sprinkler_master_switch
      unique_id: sprinkler_master_switch_id
      turn_on:
        - if:
            - condition: state
              entity_id: timer.sprinkler_valve_time
              state: paused
          then:
            - action: timer.start
              target:
                entity_id: timer.sprinkler_valve_time
      turn_off:
        - if:
            - condition: state
              entity_id: timer.sprinkler_valve_time
              state: active
          then:
            - action: timer.pause
              target:
                entity_id: timer.sprinkler_valve_time





  - button:
      - name: Sprinkler Skip Valve
        default_entity_id: button.sprinkler_skip_valve
        unique_id: sprinkler_skip_valve_id
        icon: mdi:skip-next
        availability: >
          {{ is_state('timer.sprinkler_valve_time', ['paused','active'] ) }}
        press:
          - action: timer.finish
            target:
              entity_id: timer.sprinkler_valve_time
          - action: script.sprinkler_log_message
            data:
              message: Pressed Skip
              user: |-
                {{
                  states.person 
                  | selectattr( "attributes.user_id", "==", context.user_id)
                  | map(attribute="attributes.friendly_name")
                  | first
                }}

      - name: Sprinkler All Stop
        default_entity_id: button.sprinkler_all_stop
        unique_id: sprinkler_all_stop_id
        icon: mdi:stop
        availability: "{{ is_state('timer.sprinkler_valve_time', ['paused','active'] ) }}"
        press:
          - action: timer.cancel
            target:
              entity_id: timer.sprinkler_valve_time

          - action: script.sprinkler_log_message
            data:
              message: Pressed Stop
              user: |-
                {{
                  states.person
                  | selectattr( "attributes.user_id", "==", context.user_id)
                  | map(attribute="attributes.friendly_name")
                  | first
                }}



      - name: Sprinkler Timer Pause
        default_entity_id: button.sprinkler_timer_pause
        unique_id: sprinkler_timer_pause_id
        icon: "{{ 'mdi:pause-circle' if is_state('timer.sprinkler_valve_time','active' ) else 'mdi:play-circle' }}"
        availability: "{{ is_state('timer.sprinkler_valve_time', ['paused','active'] ) }}"
        press:
          - action: script.sprinkler_log_message
            data:
              message: "Pressed {{ 'Pause' if is_state('timer.sprinkler_valve_time','active') else 'Resume' }}"
              user: |-
                {{
                  states.person 
                  | selectattr( "attributes.user_id", "==", context.user_id)
                  | map(attribute="attributes.friendly_name")
                  | first
                }}
          - action: >-
              timer.{{ 'start' if
              is_state('timer.sprinkler_valve_time','paused') else 'pause' }}
            target:
              entity_id: timer.sprinkler_valve_time




  #================ UI Templates ==============================================

  # This generates the count-down timer.
  # MUST EXCLUDE FROM RECORDER
  - trigger:
    - platform: time_pattern
      seconds: '/1'
    sensor:
    - name: Sprinkler Remaining Time
      default_entity_id: sensor.sprinkler_remaining_time
      unique_id: sprinkler_remaining_time_id
      state: >
        {% set end = state_attr('timer.sprinkler_valve_time', 'finishes_at') %}
        {% if end is not none %}
          {{ time_until(end | as_datetime) }}
        {% else %}
          {{ 'Paused' if is_state('timer.sprinkler_valve_time','paused') else 'Stopped' }}
        {% endif %}


  # ----------------- Queue Status Message ----------------------
  # Note that template triggers run in "single" mode, so there is a race where a later update doesn't get recorded
  - triggers:
      - trigger: event
        event_type: sprinkler_set_status_message
    variables:
      data: "{{ trigger.event.data }}"
      message: "{{ data.message if 'message' in data else 'Missing Message' }}"
      title: "{{ data.title if 'title' in data else 'Info' }}"
      next:  "{{ data.next if 'next' in data else '' }}"
      prog:  "{{ data.prog if 'prog' in data else '' }}"
      user:  "{{ data.user if 'user' in data else state_attr('sensor.sprinkler_queue','user') }}"

    actions:
      - if:
          - condition: template
            value_template: "{{ not 'Paused' in title }}"
        then:
        - action: script.sprinkler_log_message
          data:
            message: "{{ message }}"
            user:  "{{ user }}"

    sensor:
      - name: Sprinkler Display Message
        default_entity_id: sensor.sprinkler_display_message
        unique_id: sprinkler_display_message_id
        state: "{{ message }}"
        icon: mdi:information
        attributes:
          title: "{{ title }}"
          next:  "{{ next }}"
          prog:  "{{ prog }}"
          user:  "{{ user }}"


# ==================== Queue Running Automations =================

automation:

  # --------------- Queue changed, start running --------------
  # Essentially, any time the queue changes start the timer (which turns on the valve)
  # This can also trigger if/when the queue is empty.
  #

  - alias: "Sprinkler Run: Queue Changed"
    id: sprinkler_run_queue_changed

    triggers:
      - trigger: state
        entity_id: sensor.sprinkler_queue
        not_to:
          - unavailable
          - unknown
        not_from:
          - unavailable

    actions:


      - variables:
          queue: "{{ state_attr('sensor.sprinkler_queue', 'queue' )|default([],true) }}"

      - if:
          - "{{ queue|length > 0 }}"

        then:
          - action: timer.start
            target:
              entity_id: timer.sprinkler_valve_time
            data:
              duration: "{{ 60 * queue[0][1] }}"




  # --------------- Timer Started - turn on valve  --------------
  - alias: "Sprinkler Run: Timer Started"
    id: sprinkler_run_timer_started
    triggers:

      - trigger: event
        event_type:
          - timer.started
          - timer.restarted
        event_data:
          entity_id: timer.sprinkler_valve_time

    actions:

      # Block running any valves when the master switch is off.
      # Could this just be a simple condition?
      # Seems like this should be part of availability on the buttons.

      - if:
          - condition: state
            entity_id: switch.sprinkler_master_switch
            state: "off"
        then:
          - event: sprinkler_set_status_message
            event_data:
              message: 'Cannot start. Master switch is off. Check pressure.'
              title: Alert
          - stop: End


      - variables:
          queue: "{{ state_attr('sensor.sprinkler_queue', 'queue' )|default([],true)  }}"

      - if:
          - "{{ queue|length == 0 }}"
        then:
          - event: sprinkler_set_status_message
            event_data:
              message: "Timer Started but no sprinklers to run."
              title: Alerta

        else:
          - action: homeassistant.turn_on
            target:
              entity_id: "{{ queue[0][0] }}"


          - event: sprinkler_set_status_message
            event_data:
              title: Running
              message:  "{{ entity_name( queue[0][0] ) }}"
              next: "{{ entity_name( queue[1][0] ) if queue|length > 1 else '' }}"

              # Not really true -- fix this in the sprinkler_queue
              prog: "{{ state_attr('sensor.sprinkler_queue','prog') if queue|length > 1 else '' }}"



  # --------------- Timer Stopped/Paused  --------------
  - alias: "Sprinkler Run: Timer Stopped or Paused"
    id: sprinkler_run_timer_stopped_or_paused
    triggers:

      - trigger: event
        event_type:
          - timer.paused
          - timer.cancelled
          - timer.finished
        event_data:
          entity_id: timer.sprinkler_valve_time

    actions:
      - variables:
          queue: "{{ state_attr('sensor.sprinkler_queue', 'queue' )|default([],true)  }}"
          event_type: "{{ trigger.event.event_type }}"

      # Don't really need to do this when != paused, because the queue will turn off the item as it is removed from queue.
      # The queue does that to prevent zombie switches if the queue is somehow manually changed.
      - action: homeassistant.turn_off
        target:
          entity_id: "{{ queue[0][0] }}"

      # Add a wait_on_state here and a warning?

      - choose:
          - conditions:
              - "{{ 'paused' in event_type }}"
            sequence:
              - event: sprinkler_set_status_message
                event_data:
                  title: Paused until
                  message: "{{ (now() + timedelta(minutes=10)).strftime( '%H:%M:%S') }}"
                  next: "{{ entity_name( queue[1][0] ) if queue|length > 1 else '' }}"
                  prog: "{{ state_attr('sensor.sprinkler_queue','prog') if queue|length > 1 else '' }}"


          - conditions:
              - "{{ 'cancelled' in event_type }}"

            sequence:
              - event: sprinkler_clear_queue

              - event: sprinkler_set_status_message
                event_data:
                  message: Stopped

          - conditions:
              - "{{ 'finished' in event_type }}"

            sequence:
              - event: sprinkler_pop_queue

              - event: sprinkler_set_status_message
                event_data:
                  message: Finished




  # --------------- Master Switch Toggled --------------
  - alias: "Sprinkler Run: Master Switch Toggled"
    id: sprinkler_run_master_switch_toggled
    triggers:
      - trigger: state
        entity_id: switch.sprinkler_master_switch
        to:
          - "on"
          - "off"

    conditions:
      - condition:
        - "{{ is_state('timer.sprinkler_valve_time', ['paused','active'] ) }}"

    # Just how long to pause?
    # Another trigger if paused for a long time just kill the timer?
    actions:
      - action: "{{ 'timer.start' if trigger.to_state.state == 'on' else 'timer.pause' }}"
        target:
          entity_id: timer.sprinkler_valve_time



  # --------------- Check for zombie valve on HA restart --------------
  - alias: "Sprinkler Run: HA Started"
    id: sprinkler_run_ha_started
    triggers:
      - trigger: homeassistant
        event: start

    actions:
      - variables:
          queue: "{{ state_attr('sensor.sprinkler_queue', 'queue' )|default([],true) }}"

      - if:
          - "{{ queue|length == 0 }}"
        then:
          - stop: "Sprinklers: HA Started but queue is empty or not running"


      - if:
          - "{{ not is_state('timer.sprinkler_valve_time','idle') }}"
        then:
          - action: system_log.write
            data:
              message: "HA Restarted but Sprinkler timer still running. No changes needed."


        else:
          - variables:
              cur_valve_entity: "{{ queue[0][0] }}"
              cur_valve_name: "{{ entity_name(cur_valve_entity) }}"

          - if:
              - condition: template
                value_template: "{{ is_state(cur_valve_entity, 'on') }}"
            then:
              - action: system_log.write
                data:
                  message: "HA Restarted. Stopping Irrigation valve {{ cur_valve_name }}"
              - action: homeassistant.turn_off
                target:
                  entity_id: "{{ cur_valve_entity }}"

              # Pop the queue, and see if there's more to run
              - event: sprinkler_pop_queue

              - event: sprinkler_set_status_message
                event_data:
                  message: Shut off {{ cur_valve_name }} after HA restart..



  # --------------- Check for Valve Paused Too Long--------------
  - alias: "Sprinkler Run: Paused Too Long"
    id: sprinkler_run_paused_too_long
    triggers:
      - trigger: state
        entity_id:
          - timer.sprinkler_valve_time
        to: paused
        for:
          minutes: 10
    actions:
      - action: timer.cancel
        target:
          entity_id: timer.sprinkler_valve_time

      - event: sprinkler_set_status_message
        event_data:
          message: Cancelled pause. Waited too long.


