# ------------------------ Running the irrigation --------------------------------
#
# The key here is timer.
#   - Valve opens when timer starts, and closes when stopped or paused
#   - If timer "finishes" (not canceled) then set new queue position
#   - When queue position changes start timer?


recorder:
  exclude:
    entities:
      - switch.sprinkler_master_switch
      - sensor.sprinkler_display_message
      - sensor.sprinkler_remaining_time

logbook:
  exclude:
    entities:
      - switch.sprinkler_master_switch
      - sensor.sprinkler_display_message
      - sensor.sprinkler_remaining_time


#=====================================================================================

timer:
  sprinkler_valve_time:
    restore: true

input_number:

  # This is 1-based. Is that insane?
  sprinkler_current_queue_position:
    min: 0
    max: 50




template:


  # Master on/off. This is NOT for general use. For seasonal shut-off just turn
  # off the schedule which still allows manual operation of programs or valves.
  # The purpose here is to have an abstraction to stop all use, e.g. in the case
  # of low water pressure. It will "pause" a running timer and prevent any running
  # of schedules, programs, or valves.
  # I'm using a "switch" here because it runs actions on changes unlike a binary sensor.
  # TODO: In general, there's a time limit on a pause to prevent forgetting about it
  # and then blocking future schedules from running. What should happen here?
  # Maybe the better solution is to allow a schedule to override a pause IF the
  # pause has been running too long?
  #
  - switch:
      name: Sprinkler Master Switch
      default_entity_id: switch.sprinkler_master_switch
      unique_id: sprinkler_master_switch_id
      turn_on:
        - if:
            - condition: state
              entity_id: timer.sprinkler_valve_time
              state: paused
          then:
            - action: timer.start
              target:
                entity_id: timer.sprinkler_valve_time
      turn_off:
        - if:
            - condition: state
              entity_id: timer.sprinkler_valve_time
              state: active
          then:
            - action: timer.pause
              target:
                entity_id: timer.sprinkler_valve_time





  - button:
      - name: Sprinkler Skip Valve
        default_entity_id: button.sprinkler_skip_valve
        unique_id: sprinkler_skip_valve_id
        icon: mdi:skip-next
        availability: >
          {{ is_state('timer.sprinkler_valve_time', ['paused','active'] ) }}
        press:
          - action: timer.finish
            target:
              entity_id: timer.sprinkler_valve_time
          - action: script.sprinkler_log_message
            data:
              message: Pressed Skip
              user: |-
                {{
                  states.person 
                  | selectattr( "attributes.user_id", "==", context.user_id)
                  | map(attribute="attributes.friendly_name")
                  | first
                }}

      - name: Sprinkler All Stop
        default_entity_id: button.sprinkler_all_stop
        unique_id: sprinkler_all_stop_id
        icon: mdi:stop
        availability: "{{ is_state('timer.sprinkler_valve_time', ['paused','active'] ) }}"
        press:
          - action: timer.cancel
            target:
              entity_id: timer.sprinkler_valve_time

          - action: script.sprinkler_log_message
            data:
              message: Pressed Stop
              user: |-
                {{
                  states.person
                  | selectattr( "attributes.user_id", "==", context.user_id)
                  | map(attribute="attributes.friendly_name")
                  | first
                }}



      - name: Sprinkler Timer Pause
        default_entity_id: button.sprinkler_timer_pause
        unique_id: sprinkler_timer_pause_id
        icon: "{{ 'mdi:pause-circle' if is_state('timer.sprinkler_valve_time','active' ) else 'mdi:play-circle' }}"
        availability: "{{ is_state('timer.sprinkler_valve_time', ['paused','active'] ) }}"
        press:
          - action: script.sprinkler_log_message
            data:
              message: "Pressed {{ 'Pause' if is_state('timer.sprinkler_valve_time','active') else 'Resume' }}"
              user: |-
                {{
                  states.person 
                  | selectattr( "attributes.user_id", "==", context.user_id)
                  | map(attribute="attributes.friendly_name")
                  | first
                }}
          - action: >-
              timer.{{ 'start' if
              is_state('timer.sprinkler_valve_time','paused') else 'pause' }}
            target:
              entity_id: timer.sprinkler_valve_time




  #================ UI Templates ==============================================

  # This generates the count-down timer.
  # MUST EXCLUDE FROM RECORDER
  - trigger:
    - platform: time_pattern
      seconds: '/1'
    sensor:
    - name: Sprinkler Remaining Time
      default_entity_id: sensor.sprinkler_remaining_time
      unique_id: sprinkler_remaining_time_id
      state: >
        {% set end = state_attr('timer.sprinkler_valve_time', 'finishes_at') %}
        {% if end is not none %}
          {{ time_until(end | as_datetime) }}
        {% else %}
          {{ 'Paused' if is_state('timer.sprinkler_valve_time','paused') else 'Stopped' }}
        {% endif %}


  # ----------------- Queue Status Message ----------------------
  # Note that template triggers run in "single" mode, so there is a race where a later update doesn't get recorded
  - triggers:
      - trigger: event
        event_type: sprinkler_set_status_message
    variables:
      data: "{{ trigger.event.data }}"
      message: "{{ data.message }}"
      title: "{{ data.title if 'title' in data else 'Info' }}"
      next:  "{{ data.next if 'next' in data else '' }}"
      prog:  "{{ data.prog if 'prog' in data else '' }}"
      user:  "{{ data.user if 'user' in data else state_attr('sensor.sprinkler_queue','user') }}"

    actions:
      - if:
          - condition: template
            value_template: "{{ not 'Paused' in title }}"
        then:
        - action: script.sprinkler_log_message
          data:
            message: "{{ message }}"
            user:  "{{ user }}"

    sensor:
      - name: Sprinkler Display Message
        default_entity_id: sensor.sprinkler_display_message
        unique_id: sprinkler_display_message_id
        state: "{{ message }}"
        icon: mdi:information
        attributes:
          title: "{{ title }}"
          next:  "{{ next }}"
          prog:  "{{ prog }}"
          user:  "{{ user }}"

automation:

  # --------------- Queue changed, start running --------------
  - alias: "Sprinkler Run: Queue Changed"
    id: sprinkler_run_queue_changed

    triggers:
      - trigger: state
        entity_id: sensor.sprinkler_queue
        not_to:
          - unavailable
          - unknown
        not_from:
          - unavailable

    actions:

      # In case it's already set to 1
      - action: input_number.set_value
        target:
          entity_id: input_number.sprinkler_current_queue_position
        data:
          value: 0


      - action: input_number.set_value
        target:
          entity_id: input_number.sprinkler_current_queue_position
        data:
          value: 1

  # --------------- Queue position changed start timer  --------------
  - alias: "Sprinkler Run: Queue Position Changed"
    id: sprinkler_run_queue_position_changed
    triggers:
      - trigger: state
        entity_id: input_number.sprinkler_current_queue_position

    conditions:
      - "{{ states('input_number.sprinkler_current_queue_position' )|int(1) > 0 }}"

    actions:

      # Make sure then updated position is written to disk
      - action: homeassistant.save_persistent_states


      - variables:
          queue: "{{ state_attr('sensor.sprinkler_queue', 'queue' ) }}"
          queue_idx: "{{ states('input_number.sprinkler_current_queue_position' )|int(1) }}"

      - if:
          - "{{ queue_idx > queue|length }}"
        then:
          - event: sprinkler_set_status_message
            event_data:
              message: Completed
        else:

          - action: timer.start
            target:
              entity_id: timer.sprinkler_valve_time
            data:
              duration: "{{ 60 * queue[queue_idx-1][1] }}"



  # --------------- Timer Started - turn on valve  --------------
  - alias: "Sprinkler Run: Timer Started"
    id: sprinkler_run_timer_started
    triggers:

      - trigger: event
        event_type:
          - timer.started
          - timer.restarted
        event_data:
          entity_id: timer.sprinkler_valve_time

    actions:
      - variables:
          queue: "{{ state_attr('sensor.sprinkler_queue', 'queue' ) }}"
          queue_idx: "{{ states('input_number.sprinkler_current_queue_position' )|int(1) }}"
          cur_valve_entity: "{{ queue[queue_idx-1][0] }}"
          next_valve: "{{ [] if queue_idx == queue|length else queue[queue_idx] }}"

      # Block running any valves when the master switch is off.
      # Could this just be a simple condition?
      # Seems like this should be part of availability on the buttons.

      - if:
          - condition: state
            entity_id: switch.sprinkler_master_switch
            state: "off"
        then:
          - event: sprinkler_set_status_message
            event_data:
              message: 'Cannot start. Master switch is off. Check pressure.'
              title: Alert
          - stop: End



      - action: homeassistant.turn_on
        target:
          entity_id: "{{ cur_valve_entity }}"

      - event: sprinkler_set_status_message
        event_data:
          title: Running
          message:  "{{ entity_name(cur_valve_entity) }}"
          next: "{{ entity_name(next_valve[0]) if next_valve|length else '' }}"
          prog: "{{ state_attr('sensor.sprinkler_queue','prog') if queue|length > 1 else '' }}"

  # --------------- Timer Stopped/Paused  --------------
  - alias: "Sprinkler Run: Timer Stopped or Paused"
    id: sprinkler_run_timer_stopped_or_paused
    triggers:

      - trigger: event
        event_type:
          - timer.paused
          - timer.cancelled
          - timer.finished
        event_data:
          entity_id: timer.sprinkler_valve_time

    actions:
      - variables:
          queue: "{{ state_attr('sensor.sprinkler_queue', 'queue' ) }}"
          queue_idx: "{{ states('input_number.sprinkler_current_queue_position' )|int(1) }}"
          cur_valve_entity: "{{ queue[queue_idx-1][0] }}"
          next_valve: "{{ [] if queue_idx == queue|length else queue[queue_idx] }}"
          event_type: "{{ trigger.event.event_type }}"


      - action: homeassistant.turn_off
        target:
          entity_id: "{{ cur_valve_entity }}"

      # Add a wait_on_state here and a warning?

      - choose:
          - conditions:
              - "{{ 'paused' in event_type }}"
            sequence:
              - event: sprinkler_set_status_message
                event_data:
                  title: Paused until
                  message: "{{ (now() + timedelta(minutes=10)).strftime( '%H:%M:%S') }}"
                  next: "{{ entity_name(next_valve[0]) if next_valve|length else '' }}"
                  prog: "{{ state_attr('sensor.sprinkler_queue','prog') if queue|length > 1 else '' }}"

          - conditions:
              - "{{ 'cancelled' in event_type }}"
            sequence:
              # Set the position to the end
              # But this will trigger a change and result in a "finished" message
              # Maybe don't even need this?
              - action: input_number.set_value
                enabled: false
                target:
                  entity_id: input_number.sprinkler_current_queue_position
                data:
                  value: "{{ state_attr('sensor.sprinkler_queue', 'queue' ) | length }}"

              - event: sprinkler_set_status_message
                event_data:
                  message: Stopped

          # Move to next valve
          - conditions:
              - "{{ 'finished' in event_type }}"
            sequence:
              # This delay is to allow final counts of water used by the previous valve
              - delay:
                  seconds: 2
              - action: input_number.increment
                target:
                  entity_id: input_number.sprinkler_current_queue_position

  # --------------- Master Switch Toggled --------------
  - alias: "Sprinkler Run: Master Switch Toggled"
    id: sprinkler_run_master_switch_toggled
    triggers:
      - trigger: state
        entity_id: switch.sprinkler_master_switch
        to:
          - "on"
          - "off"

    conditions:
      - condition:
        - "{{ is_state('timer.sprinkler_valve_time', ['paused','active'] ) }}"

    # Just how long to pause?
    # Another trigger if paused for a long time just kill the timer?
    actions:
      - action: "{{ 'timer.start' if trigger.to_state.state == 'on' else 'timer.pause' }}"
        target:
          entity_id: timer.sprinkler_valve_time



  # --------------- Check for zombie valve on HA restart --------------
  - alias: "Sprinkler Run: HA Started"
    id: sprinkler_run_ha_started
    triggers:
      - trigger: homeassistant
        event: start

    actions:
      - variables:
          queue: "{{ state_attr('sensor.sprinkler_queue', 'queue' ) }}"
          queue_idx: "{{ states('input_number.sprinkler_current_queue_position' )|int(1) }}"
          cur_valve_entity: "{{ queue[queue_idx-1][0] }}"
          cur_valve_name: "{{ entity_name(cur_valve_entity) }}"

      - if:
          - "{{ not is_state('timer.sprinkler_valve_time','idle') }}"
        then:
          - action: system_log.write
            data:
              message: "HA Restarted but Sprinkler timer still running. No changes needed."
        else:
          - if:
              - condition: template
                value_template: "{{ is_state(cur_valve_entity, 'on') }}"
            then:
              - action: system_log.write
                data:
                  message: "HA Restarted. Stopping Irrigation valve {{ cur_valve_name }}"
              - action: homeassistant.turn_off
                target:
                  entity_id: "{{ cur_valve_entity }}"

              - event: sprinkler_set_status_message
                event_data:
                  message: Shut off {{ cur_valve_name }} after HA restart..

  # --------------- Check for zombie valve on HA restart --------------
  - alias: "Sprinkler Run: Paused Too Long"
    id: sprinkler_run_paused_too_long
    triggers:
      - trigger: state
        entity_id:
          - timer.sprinkler_valve_time
        to: paused
        for:
          minutes: 10
    actions:
      - action: timer.cancel
        target:
          entity_id: timer.sprinkler_valve_time

      - event: sprinkler_set_status_message
        event_data:
          message: Cancelled pause. Waited too long.


